"""
FastAPI Backend for Multi-Agent Post-Discharge Care System
"""

from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Dict, Any, List, Optional
import sys
import os
from datetime import datetime
import logging

# Add src directory to path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from multi_agent_system import MultiAgentSystem
from improved_rag_system import ImprovedRAGSystem

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize FastAPI app
app = FastAPI(
    title="Post-Discharge Care API",
    description="Multi-Agent AI System for Nephrology Patient Care",
    version="1.0.0"
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure appropriately for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global system instance
multi_agent_system = None
rag_system = None

# Pydantic models
class ChatMessage(BaseModel):
    message: str
    session_id: Optional[str] = "default"

class ChatResponse(BaseModel):
    response: str
    agent: str
    source: Optional[str] = None
    chunks_found: Optional[int] = 0
    timestamp: Optional[str] = None
    patient_found: Optional[bool] = False
    relevant_chunks: Optional[List[Dict]] = []
    web_search_results: Optional[List[Dict]] = []

class RAGQuery(BaseModel):
    query: str
    use_web_fallback: bool = True

class SystemStatus(BaseModel):
    status: str
    current_agent: str
    patient_name: Optional[str] = None
    total_interactions: int
    timestamp: str

class ResetRequest(BaseModel):
    session_id: Optional[str] = "default"

@app.on_event("startup")
async def startup_event():
    """Initialize the multi-agent system on startup"""
    global multi_agent_system, rag_system
    try:
        logger.info("Initializing Multi-Agent System...")
        multi_agent_system = MultiAgentSystem()
        rag_system = ImprovedRAGSystem()
        logger.info("Multi-Agent System initialized successfully")
    except Exception as e:
        logger.error(f"Failed to initialize system: {e}")
        raise

@app.get("/")
async def root():
    """Root endpoint"""
    return {
        "message": "Post-Discharge Care API",
        "version": "1.0.0",
        "status": "running"
    }

@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {
        "status": "healthy",
        "timestamp": datetime.now().isoformat(),
        "system_initialized": multi_agent_system is not None
    }

@app.post("/chat", response_model=ChatResponse)
async def chat_endpoint(message: ChatMessage):
    """
    Main chat endpoint for interacting with the multi-agent system
    """
    if not multi_agent_system:
        raise HTTPException(status_code=500, detail="Multi-agent system not initialized")
    
    try:
        logger.info(f"Processing chat message: {message.message[:50]}...")
        
        # Process the message through the multi-agent system
        response = multi_agent_system.process_user_input(message.message)
        
        # Convert to API response format
        api_response = ChatResponse(
            response=response.get("response", ""),
            agent=response.get("agent", "system"),
            source=response.get("source"),
            chunks_found=response.get("chunks_found", 0),
            timestamp=response.get("timestamp", datetime.now().isoformat()),
            patient_found=response.get("patient_found", False),
            relevant_chunks=response.get("relevant_chunks", []),
            web_search_results=response.get("web_search_results", [])
        )
        
        logger.info(f"Chat response generated by {api_response.agent} agent")
        return api_response
        
    except Exception as e:
        logger.error(f"Error processing chat message: {e}")
        raise HTTPException(status_code=500, detail=f"Error processing message: {str(e)}")

@app.post("/rag/query")
async def rag_query_endpoint(query: RAGQuery):
    """
    Direct RAG query endpoint for testing RAG system independently
    """
    if not rag_system:
        raise HTTPException(status_code=500, detail="RAG system not initialized")
    
    try:
        logger.info(f"Processing RAG query: {query.query[:50]}...")
        
        # Query the RAG system directly
        response = rag_system.answer_query(query.query, query.use_web_fallback)
        
        return {
            "query": query.query,
            "answer": response.get("answer", ""),
            "source": response.get("source", ""),
            "chunks_found": response.get("chunks_found", 0),
            "chunks_retrieved": response.get("chunks_retrieved", 0),
            "relevant_chunks": response.get("relevant_chunks", []),
            "web_search_results": response.get("web_search_results", []),
            "timestamp": response.get("timestamp", datetime.now().isoformat())
        }
        
    except Exception as e:
        logger.error(f"Error processing RAG query: {e}")
        raise HTTPException(status_code=500, detail=f"Error processing RAG query: {str(e)}")

@app.get("/system/status", response_model=SystemStatus)
async def get_system_status():
    """
    Get current system status and conversation state
    """
    if not multi_agent_system:
        raise HTTPException(status_code=500, detail="Multi-agent system not initialized")
    
    try:
        summary = multi_agent_system.get_conversation_summary()
        
        return SystemStatus(
            status="active",
            current_agent=summary.get("current_agent", "unknown"),
            patient_name=summary.get("current_patient"),
            total_interactions=summary.get("total_interactions", 0),
            timestamp=datetime.now().isoformat()
        )
        
    except Exception as e:
        logger.error(f"Error getting system status: {e}")
        raise HTTPException(status_code=500, detail=f"Error getting system status: {str(e)}")

@app.post("/system/reset")
async def reset_conversation(reset_request: ResetRequest):
    """
    Reset the conversation state
    """
    if not multi_agent_system:
        raise HTTPException(status_code=500, detail="Multi-agent system not initialized")
    
    try:
        logger.info(f"Resetting conversation for session: {reset_request.session_id}")
        
        # Reset the conversation
        multi_agent_system.reset_conversation()
        
        return {
            "status": "success",
            "message": "Conversation reset successfully",
            "session_id": reset_request.session_id,
            "timestamp": datetime.now().isoformat()
        }
        
    except Exception as e:
        logger.error(f"Error resetting conversation: {e}")
        raise HTTPException(status_code=500, detail=f"Error resetting conversation: {str(e)}")

@app.get("/patients")
async def list_patients():
    """
    Get list of available patients
    """
    if not multi_agent_system:
        raise HTTPException(status_code=500, detail="Multi-agent system not initialized")
    
    try:
        # Get patients from the patient database
        patients = multi_agent_system.patient_db.patients_data
        
        patient_list = []
        for patient in patients:
            patient_list.append({
                "name": patient.patient_name,
                "diagnosis": patient.primary_diagnosis,
                "discharge_date": patient.discharge_date
            })
        
        return {
            "patients": patient_list,
            "total_count": len(patient_list),
            "timestamp": datetime.now().isoformat()
        }
        
    except Exception as e:
        logger.error(f"Error listing patients: {e}")
        raise HTTPException(status_code=500, detail=f"Error listing patients: {str(e)}")

@app.get("/patients/{patient_name}")
async def get_patient_details(patient_name: str):
    """
    Get detailed information for a specific patient
    """
    if not multi_agent_system:
        raise HTTPException(status_code=500, detail="Multi-agent system not initialized")
    
    try:
        # Find patient by name
        patient = multi_agent_system.patient_db.find_patient_by_name(patient_name)
        
        if not patient:
            raise HTTPException(status_code=404, detail=f"Patient '{patient_name}' not found")
        
        return {
            "patient_name": patient.patient_name,
            "primary_diagnosis": patient.primary_diagnosis,
            "discharge_date": patient.discharge_date,
            "medications": patient.medications,
            "dietary_restrictions": patient.dietary_restrictions,
            "follow_up": patient.follow_up,
            "warning_signs": patient.warning_signs,
            "timestamp": datetime.now().isoformat()
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error getting patient details: {e}")
        raise HTTPException(status_code=500, detail=f"Error getting patient details: {str(e)}")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)
